# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='url',
            field=models.URLField(),
        ),
    ]
